name: CI

on:
  push:
    branches:
      - main
      - buildArmImage
    # Publish semver tags as releases.
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ''
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      #      - uses: actions/setup-python@v4
      #        with:
      #          python-version: '3.8'

      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3

      #      - name: Setup Docker
      #        uses: docker-practice/actions-setup-docker@master
      ##
      #      - name: Build Image
      #        run: |
      #          docker build -f backend/Dockerfile.scheduledworkflow -t dave917/scheduledworkflow:2.0.1 .
      ##          docker build . --file Dockerfile.cacheserver --tag ${{env.IMAGE_NAME}}
      #
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #
      #
      #      - name: Push Image
      #        run: |
      #          docker push dave917/scheduledworkflow:2.0.1
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #        with:
      #          driver: docker

      #      - name: Extract Docker metadata
      #        id: meta
      #        uses: docker/metadata-action@v4
      #        with:
      #          images: 'dave917/cacheserver'
      ##          tags: |
      ##            # set latest tag for default branch
      ##            type=raw,value=latest,enable={{is_default_branch}}
      ##            # tag event
      ##            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag
      #          flavor: |
      #            latest=auto
      #          tags: |
      #            type=schedule
      #            type=ref,event=tag
      #            type=sha,prefix=,format=long,enable=true,priority=100

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        #        env:
        #          TARGETOS: linux
        #          TARGETARCH: arm64
        with:
          context: ci/official/containers/linux_arm64
          file: ci/official/containers/linux_arm64/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: dave917/tensorflow:latest
          platforms: linux/arm64
